### ISSUE TITLE
Use simpleName to trim the tar.gz suffix

### ISSUE THREAD

**Issue by cgpu** [liuyangzzu/nanome#18]
https://github.com/liuyangzzu/nanome/blob/3c344b67c01ab68b541a5c2add856b3ce4ae9cc2/main.nf#L198

If you want to use the basename without any suffix, you can use simpleName method.

Example:
```groovy
     guppy_basecaller --output_path ${x.simpleName}_basecalled_folder \ 
```
Convert the whole folder to a tar to pass to the next process.

**Comment by liuyangzzu** [comment]
We fixed name problem on CloudOS using simpleName method.
