### ISSUE TITLE
Replace generic conda base image, with guppy to have all dependencies in 1 container

### ISSUE THREAD

**Issue by cgpu** [liuyangzzu/nanome#6]
https://github.com/liuyangzzu/nano-compare/blob/7b52f908d29c985bbc3996bfd1ec72773bbaaded/Dockerfile#L1

This is a requirement for the process named `Megalodon` so it is a good universal solution.
We may need to add extra Miniconda.

**Comment by liuyangzzu** [comment]
We build the Docker container start with Guppy containter.
